version: "2"
services:
    influxdb:
        image: influxdb
        container_name: influxdb
        ports:
          - 8086:8086
        environment:
          INFLUXDB_DB: loadrunner
          INFLUXDB_USER: user
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: admin
        volumes:
          - ./influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
          - 3000:3000
        volumes:
          - ./grafana:/var/lib/grafana  
